version: '3.8'

services:
  web:
    build: .
    # Removed ports directive - Coolify handles port forwarding automatically
    environment:
      # Frontend API URL (this will be the public URL of the backend service)
      REACT_APP_API_URL: ${REACT_APP_API_URL}
      # Site URL (this will be the public URL of the frontend service)
      REACT_APP_SITE_URL: ${REACT_APP_SITE_URL}
      # Stripe configuration
      REACT_APP_STRIPE_PUBLISHABLE_KEY: ${REACT_APP_STRIPE_PUBLISHABLE_KEY}
      # Optional: Analytics
      REACT_APP_GOOGLE_ANALYTICS_ID: ${REACT_APP_GOOGLE_ANALYTICS_ID}
      # Optional: Social Media Links
      REACT_APP_SOCIAL_TELEGRAM: ${REACT_APP_SOCIAL_TELEGRAM}
      REACT_APP_SOCIAL_GITHUB: ${REACT_APP_SOCIAL_GITHUB}
      REACT_APP_SOCIAL_LINKEDIN: ${REACT_APP_SOCIAL_LINKEDIN}
    depends_on:
      - db
    networks:
      - iacovici-network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # Use md5 authentication which is more compatible
      POSTGRES_INITDB_ARGS: "--auth-host=md5 --auth-local=md5"
    # Removed ports directive - Coolify handles port forwarding automatically
    volumes:
      - postgres_data_v3:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./init-db.sql:/docker-entrypoint-initdb.d/02-init-db.sql
    networks:
      - iacovici-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  backend:
    build: ./backend
    # Removed ports directive - Coolify handles port forwarding automatically
    environment:
      # Database configuration
      POSTGRES_HOST: db
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      # JWT configuration
      JWT_SECRET: ${JWT_SECRET}
      # Backend port
      BACKEND_PORT: 3001
      # Frontend URL for redirects (Stripe success/cancel URLs)
      FRONTEND_URL: ${FRONTEND_URL}
      # Stripe configuration
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      # Email configuration
      EMAIL_FROM_ADDRESS: ${EMAIL_FROM_ADDRESS}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      # Optional: Analytics
      GOOGLE_ANALYTICS_ID: ${GOOGLE_ANALYTICS_ID}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - iacovici-network
    restart: unless-stopped

volumes:
  postgres_data_v3:
    driver: local

networks:
  iacovici-network:
    driver: bridge