version: '3.8'

services:
  web:
    build: .
    # Removed ports directive - Coolify handles port forwarding automatically
    depends_on:
      - db
    networks:
      - iacovici-network
    restart: unless-stopped

  db:
    container_name: db
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # Removed ports directive - Coolify handles port forwarding automatically
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - iacovici-network
    restart: unless-stopped

  backend:
    build: ./backend
    # Removed ports directive - Coolify handles port forwarding automatically
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432
      JWT_SECRET: ${JWT_SECRET}
      BACKEND_PORT: 3001
    depends_on:
      - db
    networks:
      - iacovici-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  iacovici-network:
    driver: bridge